### ISSUE TITLE
Happy Code Lab Fails at Step 5:  Add Weave - Weave network gateway

### ISSUE THREAD

**Issue by lancehudson** [openweave/happy#11]
When trying to add the network gateway to weave I get:

    ~/openweave-core$ weave-network-gateway ThreadNetwork 02BorderRouter
    Traceback (most recent call last):
      File "/home/lance/openweave-core/src/test-apps/happy/bin/weave-network-gateway", line 77, in <module>
        cmd.start()
      File "/usr/local/lib/python2.7/dist-packages/happy-1.1.36-py2.7.egg/happy/Driver.py", line 417, in start
        x = self.run()
      File "/home/lance/openweave-core/src/test-apps/happy/lib/WeaveNetworkGateway.py", line 162, in run
        self.__pre_check()
      File "/home/lance/openweave-core/src/test-apps/happy/lib/WeaveNetworkGateway.py", line 130, in __pre_check
        if self.isIpAddress(self.gateway):
    AttributeError: WeaveNetworkGateway instance has no attribute 'isIpAddress'

happy-state

    State Name:  happy

    NETWORKS   Name         Type   State                                     Prefixes
      ThreadNetwork       thread      UP                       2001:0db8:0001:0002/64

        WiFiNetwork         wifi      UP                       2001:0db8:000a:000b/64
                                                                            10.0.1/24

    NODES      Name    Interface    Type                                          IPs
       01ThreadNode        wpan0  thread   2001:0db8:0001:0002:f221:4aff:fe51:ada9/64
                                           fd00:0000:fab1:0006:9bdd:f4a6:1c22:11e9/64

     02BorderRouter        wpan0  thread   fd00:0000:fab1:0006:9bdd:f4a7:1c22:11e9/64
                                           2001:0db8:0001:0002:928c:0dff:fe44:a33a/64

                           wlan0    wifi                                  10.0.1.2/24
                                           fd00:0000:fab1:0001:9bdd:f4a7:1c22:11e9/64
                                           2001:0db8:000a:000b:028f:a0ff:fe38:978c/64

         03WiFiNode        wlan0    wifi   fd00:0000:fab1:0001:9bdd:f4a8:1c22:11e9/64
                                                                          10.0.1.3/24
                                           2001:0db8:000a:000b:5e0e:ceff:fef6:f2db/64

weave-state

    State Name: weave

    NODES                Name       Weave Node Id    Pairing Code
                 01ThreadNode    99ddf4a61c2211e9          7LD74S
               02BorderRouter    99ddf4a71c2211e9          58C6EV
                   03WiFiNode    99ddf4a81c2211e9          UDL2S1

    FABRIC          Fabric Id           Global Prefix
                         fab1     fd00:0000:fab1::/48

**Comment by jenniexie** [comment]
Hi Lance:
     I will take a look later today, will let you know the update
Thanks
Jennie

**Comment by lancehudson** [comment]
I downgraded happy to db73eeb and openweave-core to 4.0.2, cleaned and rebuilt.
I didn't get the error after that.

**Comment by jenniexie** [comment]
Sorry I missed one change by mistake, a quick fix on your local would be
change *self*.isIpAddress to *IP*.isIpAddress, I will make a fix to
openweave-core repo to fix this issue.
I have double checked again for all functions using IP module util in both
openweave-core and Happy repo, that is the only one missing by mistake.

(happy) jexie@jexie0:~/github$ grep -r "self.getIPv6Subnet" .
(happy) jexie@jexie0:~/github$ grep -r "self.getIPv6IID" .
(happy) jexie@jexie0:~/github$ grep -r "self.paddingZeros" .
(happy) jexie@jexie0:~/github$ grep -r "self.dropZeros" .
(happy) jexie@jexie0:~/github$ grep -r "self.prefixMatchAddress" .
(happy) jexie@jexie0:~/github$ grep -r "self.getPrefix" .
(happy) jexie@jexie0:~/github$ grep -r "self.isIpv6" .
(happy) jexie@jexie0:~/github$ grep -r "self.isIpv4" .
(happy) jexie@jexie0:~/github$ grep -r "self.isIpAddress" .
./openweave-core/src/test-apps/happy/lib/WeaveNetworkGateway.py:        if
self.isIpAddress(self.gateway):
(happy) jexie@jexie0:~/github$ grep -r "self.isMulticast" .
(happy) jexie@jexie0:~/github$ grep -r "self.splitAddressMask" .
(happy) jexie@jexie0:~/github$ grep -r "self.MAC48toEUI64" .
(happy) jexie@jexie0:~/github$ grep -r "self.EUI64toIID" .
(happy) jexie@jexie0:~/github$ grep -r "self.IIDtoEUI64" .
(happy) jexie@jexie0:~/github$ grep -r "self.mac48_string_to_int" .
(happy) jexie@jexie0:~/github$ grep -r "self.eui64_string_to_int" .
(happy) jexie@jexie0:~/github$ grep -r "self.ipv6_addr_string_to_int" .
(happy) jexie@jexie0:~/github$ grep -r "self.int_to_eui64_string" .
(happy) jexie@jexie0:~/github$ grep -r "self.int_to_mac48_string" .
(happy) jexie@jexie0:~/github$ grep -r "self.int_to_ipv6_addr_string" .
(happy) jexie@jexie0:~/github$ grep -r "self.isDomainName" .
(happy) jexie@jexie0:~/github$ grep -r "self.getHostByName" .

**Comment by jenniexie** [comment]
FYI:
I have made fix for this issue in PR #133
https://github.com/openweave/openweave-core/pull/133

Thanks
Jennie

**Comment by lancehudson** [comment]
Awesome, thank you Jennie. I can confirm it is working now.

**Comment by jenniexie** [comment]
Thanks Lance and RS.

Thanks
Jennie
