### ISSUE TITLE
IP.prefixMatchAddress Does Not Appear to Work for IPv4 Addresses

### ISSUE THREAD

**Issue by gerickson** [openweave/happy#12]
I have code that is attempting to invoke:

```
self.getNodeAddressesOnPrefix(aPrefix, aNode)
```
where aPrefix is 192.168.1.0/24 and aNode is the node name with the following addresses:

- 2001:0db8:0001:0002:e6a2:d3ff:feaa:38c3
- 192.168.1.2
- fd00:0000:fab1:0001:e6a2:d3ff:feaa:38c3

It should return [192.168.1.2]; however, it returns [].

**Comment by jenniexie** [comment]
Hi Grant:
    Thanks for the information, seems that's something I need to fix :)
I will take a look today and get back to you tomorrow.

Thanks
Jennie

**Comment by gerickson** [comment]
I'm already on it, @jenniexie.

**Comment by gerickson** [comment]
In the fullness of time, we might want to just incorporate: https://github.com/python/cpython/blob/3.7/Lib/ipaddress.py (https://docs.python.org/3/library/ipaddress.html) and rebase the high-level Happy functions on them. 

Much of the string-based handling, such as `IP.prefixMatchAddress` is fundamentally broken for all but the simplest use cases.

**Comment by gerickson** [comment]
https://github.com/openweave/happy/pull/13
